name: checks
on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  issues: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
        
      - name: install ruff
        run: |
          pip install ruff
      
      - name: run ruff
        run: |
          ruff format --check
          ruff check
  
  typing:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
        
      - name: install dependencies
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true
          poetry install

      - name: run mypy
        run: |
          source .venv/bin/activate
          mypy .
  
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
        
      - name: install dependencies
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true
          poetry install

      - name: run pytest
        run: |
          source .venv/bin/activate
          pytest