name: release
on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: build distributions
        run: |
          python -m pip install poetry
          poetry build

      - name: upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/
    
  publish:
    name: publish
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 10
    environment: release
    permissions:
      id-token: write

    steps:
      - name: download distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/
        
      - name: publish to pypi
        uses: pypa/gh-action-pypi-publish@release/v1